apiVersion: apps/v1 #version of the Kubernetes API you're using to create this object
kind: Deployment  #What kind of object you want to create
metadata: #deployment name, helps uniquely identify the object
   name: covidvaccine

spec:  
  selector:
    matchLabels:
      app: covidvaccine


  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: covidvaccine
    spec:   #What state you desire for the object

      containers:
      - name: covidvaccine #container name
        image: 'jayanthanm/covidvaccine:v1' #image name
        ports:
        - containerPort: 8064 # demo runs on port 8064
