version: '3.8'

services:
    
    
 

    postgres:        
        image: postgres:14.5
        ports:
        - 5432:5432
      
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: ROOTS
            POSTGRES_DB: coviddb

       
      
    covidvaccine:        
        build: .
        #image: imagename:tag
        ports:
        - 8064:8064
     
  
