apiVersion: apps/v1 #version of the Kubernetes API you're using to create this object
kind: Deployment  #What kind of object you want to create
metadata: #Data that helps uniquely identify the object
   name: postgres

#pod name
spec: 
  selector:
    matchLabels:
      app: postgres 

#pods description
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: postgres
    spec:  

      containers:
      - name:  postgres #container name
        image: postgres:14.5 #image name
        ports:
        - containerPort: 5432 # postgres runs on port 5432
        
        env:               
            - name: POSTGRES_USER
              value:  postgres
           
            - name: POSTGRES_PASSWORD
              value:  ROOTS
             
            - name: POSTGRES_DB
              value: coviddb
